name: bybit_copy_traders_cron

on:
  # schedule:
  #   - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      - uses: action/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: 3.x
      - name: Run tw

        run: python tw2.py