name: bybit_copy_traders_cron

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  workflow_dispatch:

jobs:
  run_python_script:
    runs-on: ubuntu-latest

    permissions: read-all|write-all

    steps:
      - uses: actions/labeler@v4
          with:
            repo-token: ${{ secrets.byb }}

    
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.x  # Use the desired Python version

  
      - name: Install dependencies
        run: pip3 install requests
      - name: Install dc
        run: pip install discord-webhook


      - name: Run Python script
        run: python tw2.py